feat: Card 클래스 차원에서 builder 적용
ref. https://blog.leocat.kr/notes/2018/09/02/lombok-using-builder-and-noargsconstructor-together

- @Builder 사용 시 Jpa에서 빈 생성자를 필요로 하므로 @NoArgsConstructor 추가
- @Builder, @NoArgsConstructor 만 사용할 경우 아래 에러 발생 -> @AllArgsConstructor 추가

```java
error: constructor Card in class Card cannot be applied to given types;
@Builder
^
  required: no arguments
  found: Long,String,String,CardStatus,Integer,LocalDate
  reason: actual and formal argument lists differ in length
```